FROM eecs388/project1

# If you need to do any additional setup for development
# in the container like installing additional programs,
# do it in this file so that the changes are persisted.
#
# NOTE: you should *NOT* be installing additional pip modules
# here; everything available to you in grading is already installed.
# Installing additional modules may cause your code to become ungradeable.
#
# Example: to install Emacs, we might add:
#    RUN sudo apt-get update && sudo apt-get install -y emacs

RUN sudo apt-get update
RUN sudo apt install nodejs
RUN sudo apt install npm
RUN pip3 install flask